import type { Command } from './types';
import { normalize } from './utils';

const rows: [string, string, string, Command['role'], string, string, string?][] = [
  ['start','شروع','', 'member','general','خوش‌آمد و راه‌اندازی'],
  ['help','راهنما','دستورات|کمک', 'member','general','راهنمای دسته‌بندی‌شده','help admin'],
  ['ping','پینگ','', 'member','general','وضعیت پاسخ‌گویی'],
  ['id','ایدی','آیدی|شناسه', 'member','general','شناسهٔ شما، گروه و پیام ریپلای'],
  ['info','اطلاعات','گروه', 'member','general','وضعیت گروه و تنظیمات عمومی'],
  ['rules','قوانین','', 'member','general','نمایش قوانین'],
  ['report','گزارش','ریپورت', 'member','general','گزارش پیام با ریپلای به مدیران'],
  ['profile','پروفایل','من', 'member','economy','پروفایل، سطح، برد و باخت'],
  ['balance','موجودی','کیف پول|الماس', 'member','economy','سکه و الماس بدون ارزش نقدی'],
  ['daily','روزانه','جایزه روزانه', 'member','economy','دریافت سکه هر ۲۴ ساعت'],
  ['leaderboard','لیدربرد','برترین ها|رتبه بندی', 'member','economy','رتبه‌بندی همان گروه؛ برد یا فعالیت','leaderboard xp'],
  ['rank','رتبه','', 'member','economy','رتبهٔ شما در گروه'],
  ['games','بازیها','بازی ها|بازی‌ها', 'member','games','شش بازی بومی تلگرام و قوانین'],
  ['duel','دوئل','دوعل|نبرد', 'member','games','دوئل دو نفره با سکهٔ مجازی','duel 🎲 50'],
  ['cancelduel','لغو دوئل','انصراف', 'member','games','لغو دوئل قبل از پیوستن حریف'],
  ['play','تمرین','تاس|dice', 'member','games','تمرین بدون شرط و بدون پاداش','play 🎯'],
  ['joke','جوک','لطیفه', 'member','fun','شوخی کوتاه و دوستانه'],
  ['fact','دانستنی','فکت', 'member','fun','دانستنی کوتاه'],
  ['truth','حقیقت','', 'member','fun','پرسش بازی حقیقت'],
  ['dare','جرات','جرئت', 'member','fun','چالش دوستانه'],
  ['choose','انتخاب','یکی رو بگو', 'member','fun','انتخاب تصادفی از گزینه‌ها','choose چای | قهوه'],
  ['font','فونت','فونت ساز|فونتسازی', 'member','fun','ساخت فونت فانتزی و خفن برای متن','font سلام'],
  ['calc','حساب','ماشین حساب', 'member','tools','ماشین حساب امن','calc (12+3)*2'],
  ['time','ساعت','زمان', 'member','tools','زمان تهران و UTC'],
  ['notes','یادداشتها','یادداشت ها', 'member','tools','فهرست یادداشت‌های گروه'],
  ['getnote','یادداشت','', 'member','tools','خواندن یادداشت ذخیره‌شده','getnote لینکها'],
  ['download','دانلود','dl|دانلودر|downloader|ytdl|یوتیوب|اینستا', 'member','tools','دانلودر یوتیوب/اینستا/تیک‌تاک/توییتر','download https://...'],
  ['config','کانفیگ','vless|vmess|ss|trojan|ساخت کانفیگ|کانفیگ ساز|v2ray', 'member','tools','ساخت کانفیگ خفن VLESS/VMess/SS/Trojan','config example.com'],
  ['proxy','پروکسی','mtproto|پروکسی ساز|proxygen', 'member','tools','لیست پروکسی MTProto و ساخت پروکسی','proxy'],
  ['sub','ساب','subscription|ساب لینک', 'member','tools','ساخت ساب لینک از کانفیگ‌ها','sub'],
  ['self','سلف','سلف بات|فعالسازی سلف', 'member','self','کد اتصال یک‌بارمصرف سلف جدا؛ فقط خصوصی - سلف جدا از بات و اپ'],
  ['selfstatus','وضعیت سلف','', 'member','self','اعتبار و ساعت پایان اجارهٔ سلف جدا'],
  ['selfstop','توقف سلف','', 'member','self','ابطال دسترسی سلف جدا و پایان اجاره'],
  ['panel','پنل','مدیریت', 'admin','admin','پنل اینلاین دسته‌بندی‌شده'],
  ['settings','تنظیمات','', 'admin','admin','نمایش تنظیمات فعلی'],
  ['lock','قفل','', 'admin','security','فعال‌کردن یک فیلتر','lock لینک'],
  ['unlock','بازکردن','باز کن', 'admin','security','خاموش‌کردن یک فیلتر','unlock استیکر'],
  ['locks','قفلها','قفل ها', 'admin','security','فهرست قفل‌ها'],
  ['lockall','قفل همه','قفلهمه|بستن همه', 'admin','security','قفل کردن همهٔ فیلترهای امنیتی'],
  ['unlockall','بازکردن همه','بازهمه|باز کردن همه', 'admin','security','باز کردن همهٔ فیلترها'],
  ['preset','پروفایل امنیت','حالت امنیت', 'admin','security','الگوی متعادل، سخت‌گیر یا دوستانه','preset strict'],
  ['warn','اخطار','هشدار', 'admin','moderation','اخطار به کاربر با ریپلای یا شناسه'],
  ['unwarn','کسر اخطار','', 'admin','moderation','کم‌کردن یک اخطار'],
  ['warns','اخطارها','', 'admin','moderation','نمایش تعداد اخطار'],
  ['clearwarns','پاک اخطار','', 'admin','moderation','صفر کردن اخطارهای یک کاربر'],
  ['ban','بن','مسدود', 'admin','moderation','مسدودکردن عضو'],
  ['unban','آزاد','رفع بن', 'admin','moderation','رفع مسدودی بدون افزودن خودکار'],
  ['kick','اخراج','', 'admin','moderation','اخراج با امکان بازگشت'],
  ['mute','سکوت','میوت', 'admin','moderation','محدودکردن ارسال؛ دقیقهٔ دلخواه','mute 30'],
  ['unmute','رفع سکوت','آنمیوت', 'admin','moderation','بازگرداندن دسترسی معمول گروه'],
  ['tempban','بن موقت','', 'admin','moderation','مسدودی موقت؛ دقیقهٔ دلخواه','tempban 60'],
  ['pin','پین','سنجاق', 'admin','moderation','سنجاق پیام ریپلای'],
  ['silentpin','پین بیصدا','پین بی صدا', 'admin','moderation','سنجاق بدون اعلان'],
  ['unpin','حذف پین','برداشتن پین', 'admin','moderation','برداشتن سنجاق پیام ریپلای'],
  ['unpinall','حذف همه پینها','', 'admin','moderation','برداشتن همهٔ سنجاق‌ها با تأیید'],
  ['delete','پاک','حذف پیام', 'admin','moderation','حذف پیام ریپلای'],
  ['purge','پاکسازی','پاک سازی|حذف', 'admin','moderation','حذف قدیمی‌ترین پیام‌های ثبت‌شدهٔ قابل‌حذف با تأیید','purge 1000'],
  ['blacklist','دیمن','بلک لیست|لیست سیاه', 'admin','security','ریپلای: مسدودکردن متن دقیق یا استیکر'],
  ['unblacklist','آندیمون','رفع دیمن|حذف سیاه', 'admin','security','ریپلای: خروج متن یا استیکر از لیست سیاه'],
  ['blacklists','لیست سیاهها','سیاه ها', 'admin','security','نمایش فهرست مسدودها'],
  ['addword','کلمه ممنوع','', 'admin','security','مسدودکردن عبارت در متن و کپشن','addword تبلیغات'],
  ['delword','حذف کلمه','', 'admin','security','برداشتن عبارت ممنوع'],
  ['trust','اعتماد','', 'admin','security','معافیت کاربر از فیلترها؛ بدون اختیار مدیریتی'],
  ['untrust','لغو اعتماد','', 'admin','security','لغو معافیت'],
  ['trusted','معتمدها','', 'admin','security','فهرست کاربران معتمد'],
  ['welcome','خوشامد','خوش آمد', 'admin','settings','متن خوش‌آمد با {name} و {group}؛ off برای خاموش','welcome سلام {name}'],
  ['goodbye','خداحافظی','', 'admin','settings','متن خروج؛ off برای خاموش'],
  ['setrules','تنظیم قوانین','ثبت قوانین', 'admin','settings','ثبت متن قوانین'],
  ['antiflood','ضداسپم','ضد اسپم', 'admin','settings','روشن یا خاموش کردن ضدسیل'],
  ['floodlimit','حد اسپم','', 'admin','settings','تعداد پیام مجاز در پنجرهٔ ۱۰ ثانیه','floodlimit 6'],
  ['warnlimit','حد اخطار','', 'admin','settings','حد اخطار برای مجازات','warnlimit 3'],
  ['warnaction','مجازات اخطار','', 'admin','settings','مجازات mute یا ban'],
  ['mutetime','زمان سکوت','', 'admin','settings','مدت سکوت خودکار به دقیقه'],
  ['cooldown','فاصله پیام','', 'admin','settings','حذف پیام‌های پشت‌سرهم با فاصلهٔ کمتر از N ثانیه','cooldown 3'],
  ['captcha','کپچا','تایید ورود', 'admin','settings','تأیید ورود دکمه‌ای روشن یا خاموش'],
  ['captchatime','زمان کپچا','', 'admin','settings','مهلت تأیید ورود به ثانیه'],
  ['raid','ضدهجوم','ضد هجوم', 'admin','settings','روشن: اخراج تازه‌واردها تا خاموش‌شدن'],
  ['quiet','سکوت گروه','', 'admin','settings','حذف پیام اعضای عادی؛ مدیرها معاف'],
  ['night','شب','حالت شب', 'admin','settings','سکوت شبانه طبق زمان گروه','night 0 7'],
  ['timezone','منطقه زمانی','', 'admin','settings','فاصله از UTC به دقیقه؛ تهران ۲۱۰'],
  ['gamezone','بازی گروه','', 'admin','settings','فعال یا غیرفعال‌کردن دوئل'],
  ['maxbet','سقف شرط','', 'admin','settings','سقف سکهٔ مجازی هر دوئل'],
  ['chatbot','سخنگو','', 'admin','settings','پاسخ‌های آماده هنگام ریپلای به بات؛ روشن/خاموش'],
  ['style','لحن','', 'admin','settings','لحن friendly، formal یا playful'],
  ['reports','گزارشگیری','', 'admin','settings','فعال یا غیرفعال‌کردن گزارش عضو'],
  ['commandmode','حالت دستور','', 'admin','settings','slash: فقط اسلش؛ all: با و بدون اسلش'],
  ['joinmode','درخواست عضویت','', 'admin','settings','manual، approve یا decline'],
  ['approve','تایید عضو','', 'admin','moderation','قبول درخواست عضویت با شناسه'],
  ['decline','رد عضو','', 'admin','moderation','رد درخواست عضویت با شناسه'],
  ['say','پیام','بگو', 'admin','tools','ارسال متن از طرف بات؛ انتهای «؛پین» برای سنجاق'],
  ['schedule','زمانبندی','زمان بندی', 'admin','tools','یک پیام زمان‌بندی‌شده پس از N دقیقه','schedule 30 جلسه شروع شد'],
  ['schedules','زمانبندیها','', 'admin','tools','فهرست پیام‌های زمان‌بندی‌شده'],
  ['unschedule','لغو زمانبندی','', 'admin','tools','لغو پیام زمان‌بندی‌شده با شناسه'],
  ['addnote','ثبت یادداشت','', 'admin','tools','یادداشت نام | متن','addnote لینک | https://example.org'],
  ['delnote','حذف یادداشت','', 'admin','tools','حذف یادداشت با نام'],
  ['addanswer','ثبت پاسخ','', 'admin','tools','پاسخ خودکار عبارت دقیق | پاسخ','addanswer سلام | سلام رفیق ✨'],
  ['delanswer','حذف پاسخ','', 'admin','tools','حذف پاسخ خودکار با عبارت'],
  ['answers','پاسخها','پاسخ ها', 'admin','tools','فهرست پاسخ‌های خودکار'],
  ['title','نام گروه','', 'admin','admin','تغییر عنوان گروه'],
  ['description','توضیح گروه','', 'admin','admin','تغییر توضیح گروه'],
  ['invite','لینک دعوت','', 'admin','admin','ساخت لینک دعوت بات'],
  ['revokeinvite','تعویض دعوت','', 'admin','admin','تعویض و ابطال لینک اصلی قبلی بات'],
  ['promote','ارتقا','', 'admin','admin','ارتقای عضو؛ فقط سازندهٔ گروه یا مالک سراسری'],
  ['demote','عزل','', 'admin','admin','عزل ادمین منصوب بات؛ فقط سازنده یا مالک'],
  ['ownerhelp','راهنمای اونر','', 'owner','owner','فهرست فرمان‌های اختصاصی مالک'],
  ['ownerstats','آمار اونر','', 'owner','owner','آمار کل ربات'],
  ['groups','گروهها','گروه ها', 'owner','owner','فهرست گروه‌های ثبت‌شده'],
  ['send','ارسال','', 'owner','owner','ارسال به گروه شناخته‌شده با شناسه','send -100123 متن'],
  ['sendpin','ارسال پین','', 'owner','owner','ارسال و سنجاق در گروه مقصد','sendpin -100123 متن'],
  ['leave','خروج گروه','', 'owner','owner','خروج بات از گروه مقصد با تأیید'],
  ['grant','دادن الماس','', 'owner','owner','افزودن الماس به شناسهٔ کاربر','grant 123 5'],
  ['take','کسر الماس','', 'owner','owner','کسر الماس کاربر؛ بدون موجودی منفی'],
  ['setcoins','تنظیم سکه','', 'owner','owner','تنظیم موجودی سکهٔ کاربر'],
  ['givecoins','دادن سکه','', 'owner','owner','افزودن سکه به کاربر'],
  ['maintenance','تعمیرات','', 'owner','owner','توقف دستورهای عمومی؛ حفاظت گروه ادامه دارد'],
  ['diamondodds','سختی الماس','', 'owner','owner','شانس یک در N؛ ۵۰ پیش‌فرض، حداقل ۵۰'],
  ['dueltime','مهلت دوئل','', 'owner','owner','مهلت هر دوئل به ثانیه'],
  ['globalbet','سقف کلی شرط','', 'owner','owner','سقف سراسری شرط مجازی'],
  ['dailycoins','سکه روزانه','', 'owner','owner','مقدار پاداش روزانهٔ سکه'],
  ['freeze','توقیف','', 'owner','owner','توقف بازی و اجارهٔ سلف یک کاربر'],
  ['unfreeze','رفع توقیف','', 'owner','owner','رفع توقف کاربر'],
  ['inspect','بررسی کاربر','', 'owner','owner','وضعیت اقتصادی و دسترسی کاربر'],
  ['audit','رویدادها','', 'owner','owner','گزارش ممیزی عملیات حساس'],
  ['ledger','دفتر مالی','', 'owner','owner','آخرین گردش سکه و الماس یک کاربر'],
  ['export','خروجی تنظیمات','', 'owner','owner','خروجی JSON تنظیمات گروه؛ بدون اسرار'],
  ['revoke','ابطال دسترسی','', 'owner','owner','ابطال توکن‌های کنسول مالک و سلف جدا'],
  ['stopself','قطع سلف','', 'owner','owner','قطع اجارهٔ فعال یک کاربر'],
  ['terminal','کنسول مالک','', 'owner','owner','کد اتصال کنسول مالک؛ فقط خصوصی — بات جدا'],
  ['brand','نام بات','', 'owner','owner','ویرایش نام عمومی ربات'],
  ['bio','بیو بات','', 'owner','owner','ویرایش توضیح کوتاه ربات'],
  ['botdescription','درباره بات','', 'owner','owner','ویرایش توضیح کامل ربات'],
  ['synccommands','نصب منو','', 'owner','owner','نصب منوی دستورات انگلیسی تلگرام'],
  ['jobs','کارهای ربات','', 'owner','owner','دیدن صف پاک‌سازی و زمان‌بندی'],
  ['canceljob','لغو کار','', 'owner','owner','توقف یک کار صف؛ حذف انجام‌شده برگشت ندارد'],
  ['health','سلامت','', 'owner','owner','بررسی اتصال بات و وضعیت وبهوک'],
  ['resetgroup','بازنشانی گروه','', 'owner','owner','بازگشت تنظیمات گروه به پیش‌فرض با تأیید'],
  ['blockgroup','توقف گروه','', 'owner','owner','توقف پردازش یک گروه با تأیید'],
  ['unblockgroup','فعالسازی گروه','', 'owner','owner','ازسرگیری پردازش گروه'],
  ['resetboard','بازنشانی رتبه','', 'owner','owner','صفرکردن امتیاز گروه با تأیید؛ کیف پول حفظ می‌شود'],
  ['demgram','دمگرام','اپ|app|کلاینت|client|demgram client', 'member','general','دانلود اپ DemGram جدا - اپ جدا، بات جدا، سلف جدا، یه ورکر - دانلودر + کانفیگ ساز'],
];
export const COMMANDS: Command[] = rows.map(([name, fa, aliases, role, category, description, usage]) => ({ name, fa, aliases: aliases ? aliases.split('|') : [], role, category, description, usage }));
const index = COMMANDS.flatMap(c => [c.name, c.fa, ...c.aliases].map(alias => ({ alias: normalize(alias).toLowerCase(), command: c }))).sort((a, b) => b.alias.length - a.alias.length);
export interface Parsed { command: Command; args: string; slashed: boolean }
export function parseCommand(text: string, botUsername?: string): Parsed | undefined {
  let input = normalize(text), slashed = input.startsWith('/');
  if (slashed) {
    input = input.slice(1);
    const addressed = /^([^\s@]+)@([a-z0-9_]+)(.*)$/i.exec(input);
    if (addressed) { if (!botUsername || addressed[2].toLowerCase() !== botUsername.toLowerCase()) return; input = addressed[1] + addressed[3]; }
  }
  const lowered = input.toLowerCase();
  const found = index.find(x => lowered === x.alias || lowered.startsWith(x.alias + ' '));
  if (!found) return;
  return { command: found.command, args: input.slice(found.alias.length).trim(), slashed };
}
